# Pokémon Explorer
<a href="https://pokeapi.co/"> Visit Pokémon API </a>

In [1]:
import pandas as pd
import requests

In [2]:
url = 'https://pokeapi.co/api/v2/pokemon?limit=100'

In [3]:
res = requests.get(url)
res

In [4]:
pokemon = res.json()
pokemon

{'count': 1351,
 'next': 'https://pokeapi.co/api/v2/pokemon?offset=100&limit=100',
 'previous': None,
 'results': [{'name': 'bulbasaur',
   'url': 'https://pokeapi.co/api/v2/pokemon/1/'},
  {'name': 'ivysaur', 'url': 'https://pokeapi.co/api/v2/pokemon/2/'},
  {'name': 'venusaur', 'url': 'https://pokeapi.co/api/v2/pokemon/3/'},
  {'name': 'charmander', 'url': 'https://pokeapi.co/api/v2/pokemon/4/'},
  {'name': 'charmeleon', 'url': 'https://pokeapi.co/api/v2/pokemon/5/'},
  {'name': 'charizard', 'url': 'https://pokeapi.co/api/v2/pokemon/6/'},
  {'name': 'squirtle', 'url': 'https://pokeapi.co/api/v2/pokemon/7/'},
  {'name': 'wartortle', 'url': 'https://pokeapi.co/api/v2/pokemon/8/'},
  {'name': 'blastoise', 'url': 'https://pokeapi.co/api/v2/pokemon/9/'},
  {'name': 'caterpie', 'url': 'https://pokeapi.co/api/v2/pokemon/10/'},
  {'name': 'metapod', 'url': 'https://pokeapi.co/api/v2/pokemon/11/'},
  {'name': 'butterfree', 'url': 'https://pokeapi.co/api/v2/pokemon/12/'},
  {'name': 'weedle', 'url': 'https://pokeapi.co/api/v2/pokemon/13/'},
  {'name': 'kakuna', 'url': 'https://pokeapi.co/api/v2/pokemon/14/'},
  {'name': 'beedrill', 'url': 'https://pokeapi.co/api/v2/pokemon/15/'},
  {'name': 'pidgey', 'url': 'https://pokeapi.co/api/v2/pokemon/16/'},
  {'name': 'pidgeotto', 'url': 'https://pokeapi.co/api/v2/pokemon/17/'},
  {'name': 'pidgeot', 'url': 'https://pokeapi.co/api/v2/pokemon/18/'},
  {'name': 'rattata', 'url': 'https://pokeapi.co/api/v2/pokemon/19/'},
  {'name': 'raticate', 'url': 'https://pokeapi.co/api/v2/pokemon/20/'},
  {'name': 'spearow', 'url': 'https://pokeapi.co/api/v2/pokemon/21/'},
  {'name': 'fearow', 'url': 'https://pokeapi.co/api/v2/pokemon/22/'},
  {'name': 'ekans', 'url': 'https://pokeapi.co/api/v2/pokemon/23/'},
  {'name': 'arbok', 'url': 'https://pokeapi.co/api/v2/pokemon/24/'},
  {'name': 'pikachu', 'url': 'https://pokeapi.co/api/v2/pokemon/25/'},
  {'name': 'raichu', 'url': 'https://pokeapi.co/api/v2/pokemon/26/'},
  {'name': 'sandshrew', 'url': 'https://pokeapi.co/api/v2/pokemon/27/'},
  {'name': 'sandslash', 'url': 'https://pokeapi.co/api/v2/pokemon/28/'},
  {'name': 'nidoran-f', 'url': 'https://pokeapi.co/api/v2/pokemon/29/'},
  {'name': 'nidorina', 'url': 'https://pokeapi.co/api/v2/pokemon/30/'},
  {'name': 'nidoqueen', 'url': 'https://pokeapi.co/api/v2/pokemon/31/'},
  {'name': 'nidoran-m', 'url': 'https://pokeapi.co/api/v2/pokemon/32/'},
  {'name': 'nidorino', 'url': 'https://pokeapi.co/api/v2/pokemon/33/'},
  {'name': 'nidoking', 'url': 'https://pokeapi.co/api/v2/pokemon/34/'},
  {'name': 'clefairy', 'url': 'https://pokeapi.co/api/v2/pokemon/35/'},
  {'name': 'clefable', 'url': 'https://pokeapi.co/api/v2/pokemon/36/'},
  {'name': 'vulpix', 'url': 'https://pokeapi.co/api/v2/pokemon/37/'},
  {'name': 'ninetales', 'url': 'https://pokeapi.co/api/v2/pokemon/38/'},
  {'name': 'jigglypuff', 'url': 'https://pokeapi.co/api/v2/pokemon/39/'},
  {'name': 'wigglytuff', 'url': 'https://pokeapi.co/api/v2/pokemon/40/'},
  {'name': 'zubat', 'url': 'https://pokeapi.co/api/v2/pokemon/41/'},
  {'name': 'golbat', 'url': 'https://pokeapi.co/api/v2/pokemon/42/'},
  {'name': 'oddish', 'url': 'https://pokeapi.co/api/v2/pokemon/43/'},
  {'name': 'gloom', 'url': 'https://pokeapi.co/api/v2/pokemon/44/'},
  {'name': 'vileplume', 'url': 'https://pokeapi.co/api/v2/pokemon/45/'},
  {'name': 'paras', 'url': 'https://pokeapi.co/api/v2/pokemon/46/'},
  {'name': 'parasect', 'url': 'https://pokeapi.co/api/v2/pokemon/47/'},
  {'name': 'venonat', 'url': 'https://pokeapi.co/api/v2/pokemon/48/'},
  {'name': 'venomoth', 'url': 'https://pokeapi.co/api/v2/pokemon/49/'},
  {'name': 'diglett', 'url': 'https://pokeapi.co/api/v2/pokemon/50/'},
  {'name': 'dugtrio', 'url': 'https://pokeapi.co/api/v2/pokemon/51/'},
  {'name': 'meowth', 'url': 'https://pokeapi.co/api/v2/pokemon/52/'},
  {'name': 'persian', 'url': 'https://pokeapi.co/api/v2/pokemon/53/'},
  {'name': 'psyduck', 'url': 'https://pokeapi.co/api/v2/pokemon/54/'},
  {'name': 'golduck', 'url': 'https://pokeapi.co/api/v2/pokemon/55/'},
  {'name': 'mankey', 'url': 'https://pokeapi.co/api/v2/pokemon/56/'},
  {'name': 'primeape', 'url': 'https://pokeapi.co/api/v2/pokemon/57/'},
  {'name': 'growlithe', 'url': 'https://pokeapi.co/api/v2/pokemon/58/'},
  {'name': 'arcanine', 'url': 'https://pokeapi.co/api/v2/pokemon/59/'},
  {'name': 'poliwag', 'url': 'https://pokeapi.co/api/v2/pokemon/60/'},
  {'name': 'poliwhirl', 'url': 'https://pokeapi.co/api/v2/pokemon/61/'},
  {'name': 'poliwrath', 'url': 'https://pokeapi.co/api/v2/pokemon/62/'},
  {'name': 'abra', 'url': 'https://pokeapi.co/api/v2/pokemon/63/'},
  {'name': 'kadabra', 'url': 'https://pokeapi.co/api/v2/pokemon/64/'},
  {'name': 'alakazam', 'url': 'https://pokeapi.co/api/v2/pokemon/65/'},
  {'name': 'machop', 'url': 'https://pokeapi.co/api/v2/pokemon/66/'},
  {'name': 'machoke', 'url': 'https://pokeapi.co/api/v2/pokemon/67/'},
  {'name': 'machamp', 'url': 'https://pokeapi.co/api/v2/pokemon/68/'},
  {'name': 'bellsprout', 'url': 'https://pokeapi.co/api/v2/pokemon/69/'},
  {'name': 'weepinbell', 'url': 'https://pokeapi.co/api/v2/pokemon/70/'},
  {'name': 'victreebel', 'url': 'https://pokeapi.co/api/v2/pokemon/71/'},
  {'name': 'tentacool', 'url': 'https://pokeapi.co/api/v2/pokemon/72/'},
  {'name': 'tentacruel', 'url': 'https://pokeapi.co/api/v2/pokemon/73/'},
  {'name': 'geodude', 'url': 'https://pokeapi.co/api/v2/pokemon/74/'},
  {'name': 'graveler', 'url': 'https://pokeapi.co/api/v2/pokemon/75/'},
  {'name': 'golem', 'url': 'https://pokeapi.co/api/v2/pokemon/76/'},
  {'name': 'ponyta', 'url': 'https://pokeapi.co/api/v2/pokemon/77/'},
  {'name': 'rapidash', 'url': 'https://pokeapi.co/api/v2/pokemon/78/'},
  {'name': 'slowpoke', 'url': 'https://pokeapi.co/api/v2/pokemon/79/'},
  {'name': 'slowbro', 'url': 'https://pokeapi.co/api/v2/pokemon/80/'},
  {'name': 'magnemite', 'url': 'https://pokeapi.co/api/v2/pokemon/81/'},
  {'name': 'magneton', 'url': 'https://pokeapi.co/api/v2/pokemon/82/'},
  {'name': 'farfetchd', 'url': 'https://pokeapi.co/api/v2/pokemon/83/'},
  {'name': 'doduo', 'url': 'https://pokeapi.co/api/v2/pokemon/84/'},
  {'name': 'dodrio', 'url': 'https://pokeapi.co/api/v2/pokemon/85/'},
  {'name': 'seel', 'url': 'https://pokeapi.co/api/v2/pokemon/86/'},
  {'name': 'dewgong', 'url': 'https://pokeapi.co/api/v2/pokemon/87/'},
  {'name': 'grimer', 'url': 'https://pokeapi.co/api/v2/pokemon/88/'},
  {'name': 'muk', 'url': 'https://pokeapi.co/api/v2/pokemon/89/'},
  {'name': 'shellder', 'url': 'https://pokeapi.co/api/v2/pokemon/90/'},
  {'name': 'cloyster', 'url': 'https://pokeapi.co/api/v2/pokemon/91/'},
  {'name': 'gastly', 'url': 'https://pokeapi.co/api/v2/pokemon/92/'},
  {'name': 'haunter', 'url': 'https://pokeapi.co/api/v2/pokemon/93/'},
  {'name': 'gengar', 'url': 'https://pokeapi.co/api/v2/pokemon/94/'},
  {'name': 'onix', 'url': 'https://pokeapi.co/api/v2/pokemon/95/'},
  {'name': 'drowzee', 'url': 'https://pokeapi.co/api/v2/pokemon/96/'},
  {'name': 'hypno', 'url': 'https://pokeapi.co/api/v2/pokemon/97/'},
  {'name': 'krabby', 'url': 'https://pokeapi.co/api/v2/pokemon/98/'},
  {'name': 'kingler', 'url': 'https://pokeapi.co/api/v2/pokemon/99/'},
  {'name': 'voltorb', 'url': 'https://pokeapi.co/api/v2/pokemon/100/'}]}

In [5]:
print(len(pokemon["results"]))

100

In [6]:
df = pd.DataFrame(pokemon["results"])

df

          name                                     url
0    bulbasaur    https://pokeapi.co/api/v2/pokemon/1/
1      ivysaur    https://pokeapi.co/api/v2/pokemon/2/
2     venusaur    https://pokeapi.co/api/v2/pokemon/3/
3   charmander    https://pokeapi.co/api/v2/pokemon/4/
4   charmeleon    https://pokeapi.co/api/v2/pokemon/5/
..         ...                                     ...
95     drowzee   https://pokeapi.co/api/v2/pokemon/96/
96       hypno   https://pokeapi.co/api/v2/pokemon/97/
97      krabby   https://pokeapi.co/api/v2/pokemon/98/
98     kingler   https://pokeapi.co/api/v2/pokemon/99/
99     voltorb  https://pokeapi.co/api/v2/pokemon/100/

[100 rows x 2 columns]

In [12]:
data = []

for item in pokemon["results"]:
    detail = requests.get(item["url"]).json()

    data.append({
        "ID": detail["id"],
        "Name": detail["name"].title(),
        "Height": detail["height"],
        "Weight": detail["weight"],
        "Type": ", ".join(t["type"]["name"] for t in detail["types"]),
        "Abilities": ", ".join(a["ability"]["name"] for a in detail["abilities"]),
        "Image": detail["sprites"]["front_default"]
    })

df = pd.DataFrame(data)

df

,ID,Name,Height,Weight,Type,Abilities,Image
0,1,Bulbasaur,7,69,"grass, poison","overgrow, chlorophyll",https://raw.githubusercontent.com/PokeAPI/spri...
1,2,Ivysaur,10,130,"grass, poison","overgrow, chlorophyll",https://raw.githubusercontent.com/PokeAPI/spri...
2,3,Venusaur,20,1000,"grass, poison","overgrow, chlorophyll",https://raw.githubusercontent.com/PokeAPI/spri...
3,4,Charmander,6,85,fire,"blaze, solar-power",https://raw.githubusercontent.com/PokeAPI/spri...
4,5,Charmeleon,11,190,fire,"blaze, solar-power",https://raw.githubusercontent.com/PokeAPI/spri...
...,...,...,...,...,...,...,...
95,96,Drowzee,10,324,psychic,"insomnia, forewarn, inner-focus",https://raw.githubusercontent.com/PokeAPI/spri...
96,97,Hypno,16,756,psychic,"insomnia, forewarn, inner-focus",https://raw.githubusercontent.com/PokeAPI/spri...
97,98,Krabby,4,65,water,"hyper-cutter, shell-armor, sheer-force",https://raw.githubusercontent.com/PokeAPI/spri...
98,99,Kingler,13,600,water,"hyper-cutter, shell-armor, sheer-force",https://raw.githubusercontent.com/PokeAPI/spri...
99,100,Voltorb,5,104,electric,"soundproof, static, aftermath",https://raw.githubusercontent.com/PokeAPI/spri...

In [14]:
df.to_csv("pokemon.csv", index=False)

In [8]:
from IPython.display import display, Image

In [15]:
def get_pokemon_by_id(pokemon_id):
    result = df[df["ID"] == pokemon_id]

    if result.empty:
        print("Pokémon not found!")
        return

    display(result.drop(columns=["Image"]))

    print("\nPokémon Image:\n")
    display(Image(url=result.iloc[0]["Image"]))

In [16]:
get_pokemon_by_id(25)

    ID     Name  Height  Weight      Type              Abilities
24  25  Pikachu       4      60  electric  static, lightning-rod

Pokémon Image:

In [17]:
get_pokemon_by_id(1)

   ID       Name  Height  Weight           Type              Abilities
0   1  Bulbasaur       7      69  grass, poison  overgrow, chlorophyll

Pokémon Image: